### PR TITLE
Adjusted for old-style terminal window editors

### PR DESCRIPTION
**Pull request by kjcole**
I typically use editors that are configured to show files as-is. In other words, long lines are shown as long lines, not automatically word-wrapped. Also, I often find characters outside of the ASCII range still behave differently in different editors.  I manually word-wrapped the Markdown files, and converted non-ASCII characters to HTML entities. Also, in some cases, applying word-wrap and indenting fixed list numbering (e.g. LICENSE.md list numbering is correct now).

### CODE REVIEW

**Comment by kjcole** [comment]
Still learning: I had assumed that a second pull request would be a second pull request, not a bundling of the newer commits into the first pull request. So, now there are a few new README.md files, and minor changes elsewhere.

**Comment by stvnrlly** [comment]
This is good stuff, thanks @kjcole. I'm actually planning to deprecate this repo in the near future, though, as most of it has been moved directly onto the website. Check it out here: https://github.com/codefordc/codefordc-2.0/tree/master/_resources.

The `learn-github` stuff will be what remains here on Github, since the guide is reliant on the user actually being on Github. I haven't decided if I'm going to keep it in _this_ repo or make a new, streamlined repo. As a result, I'm going to hold off on merging this now.

As for the bundling of commits, that's totally fine. What Github does is group commits to the same branch into an existing PR, so the best way to make sure that they stay separate is to create different branches for your different groups of commits.

**Comment by kjcole** [comment]
Have you thought about expanding on the CodeForDC.GitHub.io page?  (I
don't know what the limitations are, regarding how much you can store
there, but it would seem a good place for GitHub-related Code for DC
content.)

**Comment by stvnrlly** [comment]
Yes, that's the old Code for DC site, but we wanted to keep it around while working on a new one. At this point, it should probably be replaced with the `codefordc-2.0` site, which is what's running at codefordc.org. We just have to make sure to do it all at once to avoid messing things up. @mattbailey0, what do you think?

**Comment by stvnrlly** [comment]
Oops, I was cleaning up branches and overzealously swept this up with those. Please feel free to propose these changes over on the current site repo.

**Pull request closed without merging**
